var chickendata = 
[
  {
    "BREED": "Ameraucana",
    "CONSERVATIONPRIORITYRANKINGS": "Not listed",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "Green, Blue",
    "EGGSIZE": "Med - Lg",
    "HENSIZE": "Medium",
    "EGGSPERYEAR": 150,
    "BROODY": "No",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy",
    "SPECIALCHARACTERISTICS": "Egg color; Muff and beard; Calm and docile"
  },
  {
    "BREED": "Ancona",
    "CONSERVATIONPRIORITYRANKINGS": "Watch",
    "USE": "Eggs",
    "EGGSHELLCOLOR": "White",
    "EGGSIZE": "Med - Lg",
    "HENSIZE": "Medium",
    "EGGSPERYEAR": 180,
    "BROODY": "No",
    "BEARSCONFINEMENT": "Will tolerate",
    "CLIMATETOLERANCE": "Cold-hardy",
    "SPECIALCHARACTERISTICS": "Very active and avoids human contact; Noted for hardiness and vigor; Good forager"
  },
  {
    "BREED": "Araucana",
    "CONSERVATIONPRIORITYRANKINGS": "Study",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "Blue",
    "EGGSIZE": "Med - Lg",
    "HENSIZE": "Small",
    "EGGSPERYEAR": 150,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Will tolerate",
    "CLIMATETOLERANCE": "Cold-hardy",
    "SPECIALCHARACTERISTICS": "Egg color; No tail; Tufted beard feathers"
  },
  {
    "BREED": "Australorp",
    "CONSERVATIONPRIORITYRANKINGS": "Recovering",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "Brown",
    "EGGSIZE": "Lg",
    "HENSIZE": "Heavy",
    "EGGSPERYEAR": 250,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy",
    "SPECIALCHARACTERISTICS": "Productive and fast growing; Active, yet very docile and friendly"
  },
  {
    "BREED": "Barbu d'Uccle Bantam",
    "CONSERVATIONPRIORITYRANKINGS": "Not listed",
    "USE": "Ornamental",
    "EGGSHELLCOLOR": "Tinted, Cream",
    "EGGSIZE": "Peewee",
    "HENSIZE": "Bantam",
    "EGGSPERYEAR": 100,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "",
    "SPECIALCHARACTERISTICS": ""
  },
  {
    "BREED": "Barnevelder",
    "CONSERVATIONPRIORITYRANKINGS": "Not listed",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "Dark Brown",
    "EGGSIZE": "Med - Lg",
    "HENSIZE": "Medium",
    "EGGSPERYEAR": 200,
    "BROODY": "No",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy",
    "SPECIALCHARACTERISTICS": "Egg color; Active, yet docile and friendly"
  },
  {
    "BREED": "Blue Andalusian",
    "CONSERVATIONPRIORITYRANKINGS": "Threatened",
    "USE": "Eggs",
    "EGGSHELLCOLOR": "Chalk White",
    "EGGSIZE": "Lg",
    "HENSIZE": "Medium",
    "EGGSPERYEAR": 150,
    "BROODY": "No",
    "BEARSCONFINEMENT": "No",
    "CLIMATETOLERANCE": "Heat-tolerant",
    "SPECIALCHARACTERISTICS": "Very rugged, robust, and active; Excels in free-range conditions"
  },
  {
    "BREED": "Brahma",
    "CONSERVATIONPRIORITYRANKINGS": "Watch",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "Brown",
    "EGGSIZE": "Med - Lg",
    "HENSIZE": "Very Heavy",
    "EGGSPERYEAR": 140,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Will tolerate",
    "CLIMATETOLERANCE": "Cold-hardy; Heat-tolerant",
    "SPECIALCHARACTERISTICS": "Meat quality; Winter layer; Calm and docile; Good setters and mothers; Slow to mature"
  },
  {
    "BREED": "Buttercup",
    "CONSERVATIONPRIORITYRANKINGS": "Threatened",
    "USE": "Eggs",
    "EGGSHELLCOLOR": "White",
    "EGGSIZE": "Sm - Med",
    "HENSIZE": "Small",
    "EGGSPERYEAR": 100,
    "BROODY": "No",
    "BEARSCONFINEMENT": "No",
    "CLIMATETOLERANCE": "Heat-tolerant",
    "SPECIALCHARACTERISTICS": "Unique buttercup-shaped comb; Very active; Excels in free-range conditions; Good forager"
  },
  {
    "BREED": "Campine",
    "CONSERVATIONPRIORITYRANKINGS": "Critical",
    "USE": "Eggs",
    "EGGSHELLCOLOR": "White",
    "EGGSIZE": "Med - Lg",
    "HENSIZE": "Small",
    "EGGSPERYEAR": 150,
    "BROODY": "No",
    "BEARSCONFINEMENT": "Will tolerate",
    "CLIMATETOLERANCE": "Cold-hardy",
    "SPECIALCHARACTERISTICS": "Good forager; Very active and smart; Must protect large combs from frostbite"
  },
  {
    "BREED": "Catalana",
    "CONSERVATIONPRIORITYRANKINGS": "Watch",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "White, Tinted",
    "EGGSIZE": "Med",
    "HENSIZE": "Medium",
    "EGGSPERYEAR": 200,
    "BROODY": "No",
    "BEARSCONFINEMENT": "No",
    "CLIMATETOLERANCE": "Heat-tolerant",
    "SPECIALCHARACTERISTICS": "Meat quality; Good forager; Very active"
  },
  {
    "BREED": "Chantecler",
    "CONSERVATIONPRIORITYRANKINGS": "Critical",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "Brown",
    "EGGSIZE": "Lg",
    "HENSIZE": "Heavy",
    "EGGSPERYEAR": 180,
    "BROODY": "No",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy",
    "SPECIALCHARACTERISTICS": "Can be eaten at any age; Winter layer; Calm and docile"
  },
  {
    "BREED": "Cochin",
    "CONSERVATIONPRIORITYRANKINGS": "Watch",
    "USE": "Meat, Ornamental",
    "EGGSHELLCOLOR": "Brown",
    "EGGSIZE": "Med - Lg",
    "HENSIZE": "Very Heavy",
    "EGGSPERYEAR": 140,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy",
    "SPECIALCHARACTERISTICS": "One of the best setters, especially for turkey and duck eggs; Slow to mature; Calm, friendly and docile"
  },
  {
    "BREED": "Cochin Bantam",
    "CONSERVATIONPRIORITYRANKINGS": "Not listed",
    "USE": "Ornamental",
    "EGGSHELLCOLOR": "Light Brown",
    "EGGSIZE": "Sm",
    "HENSIZE": "Bantam",
    "EGGSPERYEAR": 100,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "",
    "SPECIALCHARACTERISTICS": ""
  },
  {
    "BREED": "Cornish",
    "CONSERVATIONPRIORITYRANKINGS": "Common",
    "USE": "Meat",
    "EGGSHELLCOLOR": "Light Brown",
    "EGGSIZE": "Sm",
    "HENSIZE": "Very Heavy",
    "EGGSPERYEAR": 50,
    "BROODY": "No",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy",
    "SPECIALCHARACTERISTICS": "Meat quality; Loud and active; Not suitable for free-range"
  },
  {
    "BREED": "Crevecour",
    "CONSERVATIONPRIORITYRANKINGS": "Critical",
    "USE": "Ornamental",
    "EGGSHELLCOLOR": "White",
    "EGGSIZE": "Med - Lg",
    "HENSIZE": "Heavy",
    "EGGSPERYEAR": 100,
    "BROODY": "No",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Moderate",
    "SPECIALCHARACTERISTICS": "Very active and requires exercise; Crested head feathers"
  },
  {
    "BREED": "Cubalaya",
    "CONSERVATIONPRIORITYRANKINGS": "Threatened",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "White",
    "EGGSIZE": "Sm - Med",
    "HENSIZE": "Medium",
    "EGGSPERYEAR": 175,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Will tolerate",
    "CLIMATETOLERANCE": "Heat-tolerant",
    "SPECIALCHARACTERISTICS": "Meat quality; Fancy tail feathers; Can be aggressive and noisy but mild-mannered compared to other game birds"
  },
  {
    "BREED": "Delaware",
    "CONSERVATIONPRIORITYRANKINGS": "Critical",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "Brown",
    "EGGSIZE": "Lg - xLg",
    "HENSIZE": "Heavy",
    "EGGSPERYEAR": 200,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy; Heat-tolerant",
    "SPECIALCHARACTERISTICS": "Quick to mature; Can be eaten at any age; Calm friendly and docile"
  },
  {
    "BREED": "Dominique",
    "CONSERVATIONPRIORITYRANKINGS": "Watch",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "Brown",
    "EGGSIZE": "Med - Lg",
    "HENSIZE": "Medium",
    "EGGSPERYEAR": 275,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy",
    "SPECIALCHARACTERISTICS": "Good forager; Good setters and mothers; Calm and docile"
  },
  {
    "BREED": "Dorking",
    "CONSERVATIONPRIORITYRANKINGS": "Threatened",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "White",
    "EGGSIZE": "Med - Lg",
    "HENSIZE": "Heavy",
    "EGGSPERYEAR": 150,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy",
    "SPECIALCHARACTERISTICS": "Winter layer; Good forager; Red earlobes but white eggs; Five toes; Calm and docile"
  },
  {
    "BREED": "Egyptian Fayoumi",
    "CONSERVATIONPRIORITYRANKINGS": "Not listed",
    "USE": "Eggs",
    "EGGSHELLCOLOR": "Tinted",
    "EGGSIZE": "Sm",
    "HENSIZE": "Small",
    "EGGSPERYEAR": 100,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "No",
    "CLIMATETOLERANCE": "Heat-tolerant",
    "SPECIALCHARACTERISTICS": "Quick to mature; Good forager; Very active, vocal and flighty; Upright tails"
  },
  {
    "BREED": "Faverolle",
    "CONSERVATIONPRIORITYRANKINGS": "Threatened",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "Tinted, Light Brown",
    "EGGSIZE": "Med - Lg",
    "HENSIZE": "Heavy",
    "EGGSPERYEAR": 200,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy",
    "SPECIALCHARACTERISTICS": "Calm and docile; Muff and beard, feathered feet, and five toes; Winter layer; Roosters less aggressive than most"
  },
  {
    "BREED": "Hamburg",
    "CONSERVATIONPRIORITYRANKINGS": "Watch",
    "USE": "Eggs",
    "EGGSHELLCOLOR": "White",
    "EGGSIZE": "Sm - Med",
    "HENSIZE": "Small",
    "EGGSPERYEAR": 200,
    "BROODY": "No",
    "BEARSCONFINEMENT": "No",
    "CLIMATETOLERANCE": "Cold-hardy",
    "SPECIALCHARACTERISTICS": "Very active and flighty; Excels in free-range conditions"
  },
  {
    "BREED": "Holland",
    "CONSERVATIONPRIORITYRANKINGS": "Critical",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "White",
    "EGGSIZE": "Lg",
    "HENSIZE": "Medium",
    "EGGSPERYEAR": 150,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy",
    "SPECIALCHARACTERISTICS": "Good forager"
  },
  {
    "BREED": "Houdan",
    "CONSERVATIONPRIORITYRANKINGS": "Watch",
    "USE": "Ornamental",
    "EGGSHELLCOLOR": "White",
    "EGGSIZE": "Lg",
    "HENSIZE": "Very Heavy",
    "EGGSPERYEAR": 100,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Moderate",
    "SPECIALCHARACTERISTICS": "Setters, but tend to break eggs; Calm and docile; Crested head feathers, beard and five toes"
  },
  {
    "BREED": "Java",
    "CONSERVATIONPRIORITYRANKINGS": "Threatened",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "Brown",
    "EGGSIZE": "Sm - Med",
    "HENSIZE": "Heavy",
    "EGGSPERYEAR": 100,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Moderate",
    "SPECIALCHARACTERISTICS": "Good forager; Calm and docile"
  },
  {
    "BREED": "Jersey Giant",
    "CONSERVATIONPRIORITYRANKINGS": "Watch",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "Brown",
    "EGGSIZE": "xLg",
    "HENSIZE": "Very Heavy",
    "EGGSPERYEAR": 150,
    "BROODY": "No",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy",
    "SPECIALCHARACTERISTICS": "Unusually large size; Meat quality; Slow to mature; Calm and docile"
  },
  {
    "BREED": "La Fleche",
    "CONSERVATIONPRIORITYRANKINGS": "Watch",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "White",
    "EGGSIZE": "Med - Lg",
    "HENSIZE": "Medium",
    "EGGSPERYEAR": 150,
    "BROODY": "No",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Moderate",
    "SPECIALCHARACTERISTICS": "Good forager; Meat quality; Slow to mature; Very active and avoid human contact; V-comb"
  },
  {
    "BREED": "Lakenvelder",
    "CONSERVATIONPRIORITYRANKINGS": "Threatened",
    "USE": "Eggs",
    "EGGSHELLCOLOR": "White, Tinted",
    "EGGSIZE": "Med",
    "HENSIZE": "Small",
    "EGGSPERYEAR": 150,
    "BROODY": "No",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Moderate",
    "SPECIALCHARACTERISTICS": "Good forager; Active"
  },
  {
    "BREED": "Langshan",
    "CONSERVATIONPRIORITYRANKINGS": "Threatened",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "Dark Brown",
    "EGGSIZE": "Med - Lg",
    "HENSIZE": "Heavy",
    "EGGSPERYEAR": 150,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy",
    "SPECIALCHARACTERISTICS": "Slow to mature; Calm and docile"
  },
  {
    "BREED": "Leghorn",
    "CONSERVATIONPRIORITYRANKINGS": "Common (White); Recovering (non-White)",
    "USE": "Eggs",
    "EGGSHELLCOLOR": "White",
    "EGGSIZE": "Lg",
    "HENSIZE": "Medium",
    "EGGSPERYEAR": 300,
    "BROODY": "No",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy (White only); Heat-tolerant",
    "SPECIALCHARACTERISTICS": "Excellent layer; Very active; Noted for hardiness and vigor"
  },
  {
    "BREED": "Malay",
    "CONSERVATIONPRIORITYRANKINGS": "Threatened",
    "USE": "Meat",
    "EGGSHELLCOLOR": "Brown",
    "EGGSIZE": "Med",
    "HENSIZE": "Very Heavy",
    "EGGSPERYEAR": 50,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "No",
    "CLIMATETOLERANCE": "Heat-tolerant",
    "SPECIALCHARACTERISTICS": "Tallest of all chickens; Aggressive; Slow to mature"
  },
  {
    "BREED": "Maran",
    "CONSERVATIONPRIORITYRANKINGS": "Not listed",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "Dark Brown",
    "EGGSIZE": "Lg",
    "HENSIZE": "Heavy",
    "EGGSPERYEAR": 200,
    "BROODY": "No",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Moderate",
    "SPECIALCHARACTERISTICS": "Egg color; Active"
  },
  {
    "BREED": "Minorca",
    "CONSERVATIONPRIORITYRANKINGS": "Watch",
    "USE": "Eggs",
    "EGGSHELLCOLOR": "Chalk White",
    "EGGSIZE": "Lg - xLg",
    "HENSIZE": "Heavy",
    "EGGSPERYEAR": 200,
    "BROODY": "No",
    "BEARSCONFINEMENT": "Will tolerate",
    "CLIMATETOLERANCE": "Heat-tolerant",
    "SPECIALCHARACTERISTICS": "Good forager; Very active"
  },
  {
    "BREED": "Naked Neck",
    "CONSERVATIONPRIORITYRANKINGS": "Common",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "Light Brown",
    "EGGSIZE": "Med",
    "HENSIZE": "Medium",
    "EGGSPERYEAR": 100,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy; Heat-tolerant",
    "SPECIALCHARACTERISTICS": "Calm and especially easy to tame; Featherless neck"
  },
  {
    "BREED": "New Hampshire",
    "CONSERVATIONPRIORITYRANKINGS": "Watch",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "Brown",
    "EGGSIZE": "Lg - xLg",
    "HENSIZE": "Heavy",
    "EGGSPERYEAR": 150,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy; Heat-tolerant",
    "SPECIALCHARACTERISTICS": "Quick to mature; Calm and docile"
  },
  {
    "BREED": "Orpington",
    "CONSERVATIONPRIORITYRANKINGS": "Recovering",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "Brown",
    "EGGSIZE": "Lg - xLg",
    "HENSIZE": "Heavy",
    "EGGSPERYEAR": 150,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy",
    "SPECIALCHARACTERISTICS": "Meat quality; Calm and docile"
  },
  {
    "BREED": "Penedesenca",
    "CONSERVATIONPRIORITYRANKINGS": "Not listed",
    "USE": "Eggs",
    "EGGSHELLCOLOR": "Dark Brown",
    "EGGSIZE": "Med",
    "HENSIZE": "Small",
    "EGGSPERYEAR": 160,
    "BROODY": "No",
    "BEARSCONFINEMENT": "No",
    "CLIMATETOLERANCE": "Heat-tolerant",
    "SPECIALCHARACTERISTICS": "Egg color; Active and avoid human contact; Carnation comb"
  },
  {
    "BREED": "Phoenix",
    "CONSERVATIONPRIORITYRANKINGS": "Common",
    "USE": "Ornamental",
    "EGGSHELLCOLOR": "Cream, Tinted",
    "EGGSIZE": "Sm - Med",
    "HENSIZE": "Small",
    "EGGSPERYEAR": 50,
    "BROODY": "No",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Moderate",
    "SPECIALCHARACTERISTICS": "Fancy tail feathers"
  },
  {
    "BREED": "Plymouth Rock",
    "CONSERVATIONPRIORITYRANKINGS": "Recovering",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "Brown",
    "EGGSIZE": "Lg",
    "HENSIZE": "Heavy",
    "EGGSPERYEAR": 200,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy",
    "SPECIALCHARACTERISTICS": "Quick to mature; Meat quaility; Excel in free-range conditions; Docile"
  },
  {
    "BREED": "Polish",
    "CONSERVATIONPRIORITYRANKINGS": "Watch",
    "USE": "Eggs, Ornamental",
    "EGGSHELLCOLOR": "White",
    "EGGSIZE": "Med - Lg",
    "HENSIZE": "Small",
    "EGGSPERYEAR": 200,
    "BROODY": "No",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Moderate",
    "SPECIALCHARACTERISTICS": "Crested head feathers; Calm and docile; Rate of lay unreliable within breed"
  },
  {
    "BREED": "Rhode Island",
    "CONSERVATIONPRIORITYRANKINGS": "Recovering (Red); Watch (White)",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "Brown",
    "EGGSIZE": "Lg - xLg",
    "HENSIZE": "Heavy",
    "EGGSPERYEAR": 250,
    "BROODY": "No",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy; Heat-tolerant",
    "SPECIALCHARACTERISTICS": "Meat quality; Active yet docile"
  },
  {
    "BREED": "Sebright Bantam",
    "CONSERVATIONPRIORITYRANKINGS": "Watch",
    "USE": "Ornamental",
    "EGGSHELLCOLOR": "White, Cream",
    "EGGSIZE": "Peewee",
    "HENSIZE": "Bantam",
    "EGGSPERYEAR": 50,
    "BROODY": "No",
    "BEARSCONFINEMENT": "Will tolerate",
    "CLIMATETOLERANCE": "Heat-tolerant",
    "SPECIALCHARACTERISTICS": "Cocky but not aggressive"
  },
  {
    "BREED": "Silkie Bantam",
    "CONSERVATIONPRIORITYRANKINGS": "Common",
    "USE": "Ornamental",
    "EGGSHELLCOLOR": "Cream, Tinted",
    "EGGSIZE": "Peewee",
    "HENSIZE": "Bantam",
    "EGGSPERYEAR": 150,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy; Heat-tolerant",
    "SPECIALCHARACTERISTICS": "Excellent setters and mothers; Calm and docile; Hairlike plumage, black skin and bones, and five toes"
  },
  {
    "BREED": "Spanish",
    "CONSERVATIONPRIORITYRANKINGS": "Critical",
    "USE": "Eggs",
    "EGGSHELLCOLOR": "Chalk White",
    "EGGSIZE": "Lg",
    "HENSIZE": "Medium",
    "EGGSPERYEAR": 150,
    "BROODY": "No",
    "BEARSCONFINEMENT": "Will tolerate",
    "CLIMATETOLERANCE": "Heat-tolerant",
    "SPECIALCHARACTERISTICS": "Active and noisy; White faces"
  },
  {
    "BREED": "Sussex",
    "CONSERVATIONPRIORITYRANKINGS": "Recovering",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "Tan, Brown",
    "EGGSIZE": "Lg",
    "HENSIZE": "Heavy",
    "EGGSPERYEAR": 200,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy",
    "SPECIALCHARACTERISTICS": "Meat quality; Winter layer; Calm and docile"
  },
  {
    "BREED": "Welsummer",
    "CONSERVATIONPRIORITYRANKINGS": "Not listed",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "Deep Terra-Cotta",
    "EGGSIZE": "Med - Lg",
    "HENSIZE": "Medium",
    "EGGSPERYEAR": 200,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy",
    "SPECIALCHARACTERISTICS": "Egg color; Good forager; Intelligent and friendly"
  },
  {
    "BREED": "Wyandotte",
    "CONSERVATIONPRIORITYRANKINGS": "Recovering",
    "USE": "Eggs, Meat",
    "EGGSHELLCOLOR": "Brown",
    "EGGSIZE": "Lg",
    "HENSIZE": "Heavy",
    "EGGSPERYEAR": 20,
    "BROODY": "Yes",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Cold-hardy",
    "SPECIALCHARACTERISTICS": "Calm and docile; Tend to be dominant"
  },
  {
    "BREED": "Yokohama",
    "CONSERVATIONPRIORITYRANKINGS": "Common",
    "USE": "Ornamental",
    "EGGSHELLCOLOR": "Cream, Tinted",
    "EGGSIZE": "Sm - Med",
    "HENSIZE": "Small",
    "EGGSPERYEAR": 50,
    "BROODY": "No",
    "BEARSCONFINEMENT": "Yes",
    "CLIMATETOLERANCE": "Moderate",
    "SPECIALCHARACTERISTICS": "Fancy tail feathers; Walnut comb"
  }
]



